# copy from https://github.com/PHPirates/travis-ci-latex-pdf/blob/master/2-tectonic-miniconda/.travis.yml 
language: generic

before_install:
  # install fontawesome
  - sudo apt-get install texlive-binaries fonts-font-awesome

install:
  - export PATH="$HOME/miniconda/bin:$PATH"

  # Needed to check if conda already installed
  # If not yet installed, obtain Miniconda
  # and tectonic
  # From tectonic docs
  # https://tectonic-typesetting.github.io/en-US/install.html#the-anaconda-method
  - if ! command -v conda > /dev/null; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda -u;
      conda config --add channels conda-forge;
      conda config --set always_yes yes;
      conda install tectonic==0.1.10;
    fi

  # config Tectonic
  - conda info -a
  - sudo mkdir -p ~/.config/Tectonic/
  - echo "[[default_bundles]]" | sudo tee --append ~/.config/Tectonic/config.toml
  - sudo echo "url = \"https://tectonic.newton.cx/bundles/tlextras-2018.1r0/bundle.tar\"" | sudo tee --append ~/.config/Tectonic/config.toml

cache:
  directories:
    - $HOME/miniconda
    - $HOME/.cache/Tectonic

branches:
  only:
  - master
notifications:
  email: true
script:
 - bash ./
